name: Rename phase to selection-post

on:
  workflow_dispatch:

jobs:
  rename-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename directory
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git mv exams/phase exams/selection-post
          git commit -m "Rename exams/phase to exams/selection-post"
          git push
